/**
 * Cardiology Specialty Template (Spanish - Español)
 */

import type { SpecialtyTemplate } from './base-template';

export const cardiologyTemplateEs: SpecialtyTemplate = {
  specialty: 'Cardiology',
  specialistTitle: 'Cardiólogo',
  specialistTitlePlural: 'Cardiólogos',
  bodySystem: 'Corazón y Sistema Cardiovascular',

  commonSymptomPatterns: [
    'Dolor o molestia en el pecho (angina)',
    'Dificultad para respirar (disnea)',
    'Latidos cardíacos irregulares o palpitaciones',
    'Fatiga o debilidad',
    'Hinchazón en las piernas, tobillos o pies (edema)',
    'Mareos o sensación de desmayo',
    'Latidos cardíacos rápidos o lentos',
    'Dolor que se irradia al brazo, mandíbula, cuello o espalda',
    'Sudores fríos o piel pegajosa',
    'Náuseas o indigestión',
    'Desmayo o sensación de pérdida de conciencia (síncope)',
    'Dificultad para acostarse boca arriba (ortopnea)',
    'Tos persistente o sibilancias',
    'Color de piel azulado (cianosis)',
    'Reducción de la tolerancia al ejercicio',
  ],

  commonTreatmentTypes: [
    {
      type: 'medication',
      examples: [
        'Betabloqueantes (Metoprolol, Atenolol)',
        'Inhibidores de la ECA (Lisinopril, Enalapril)',
        'Antagonistas de los receptores de angiotensina II (Losartan, Valsartan)',
        'Estatinas (Atorvastatina, Rosuvastatina)',
        'Anticoagulantes (Warfarina, Apixabán)',
        'Diuréticos (Furosemida, Hidroclorotiazida)',
        'Bloqueadores de los canales de calcio (Amlodipina)',
        'Antiagregantes plaquetarios (Aspirina, Clopidogrel)',
        'Nitratos (Nitroglicerina)',
        'Antiarrítmicos (Amiodarona)',
      ],
    },
    {
      type: 'procedure',
      examples: [
        'Angioplastia (ACTP)',
        'Colocación de stent',
        'Cateterismo cardíaco',
        'Cardioversión',
        'Terapia de ablación',
        'Implantación de marcapasos',
        'Implantación de DAI (ICD)',
        'Valvuloplastia con balón',
        'TAVI (Sustitución de válvula aórtica transcatéter)',
      ],
    },
    {
      type: 'surgery',
      examples: [
        'Bypass coronario (CABG)',
        'Reparación/sustitución de válvula cardíaca',
        'Trasplante de corazón',
        'Implantación de LVAD (dispositivo de asistencia ventricular)',
        'Reparación de aneurisma',
        'Procedimiento de Maze',
        'Miectomía',
      ],
    },
    {
      type: 'lifestyle',
      examples: [
        'Dieta saludable para el corazón (DASH, Mediterránea)',
        'Programa de rehabilitación cardíaca',
        'Dejar de fumar',
        'Ejercicio aeróbico regular',
        'Manejo del estrés',
        'Control de peso',
        'Monitoreo de la presión arterial',
        'Control del colesterol',
      ],
    },
  ],

  commonRiskFactors: [
    { factor: 'Presión arterial alta (Hipertensión)', category: 'medical', description: 'La presión arterial elevada persistente daña las arterias y sobrecarga el corazón', modifiable: true },
    { factor: 'Colesterol alto (Hiperlipidemia)', category: 'medical', description: 'El colesterol LDL elevado provoca la acumulación de placa en las arterias', modifiable: true },
    { factor: 'Diabetes mellitus', category: 'medical', description: 'El azúcar alto en sangre daña los vasos sanguíneos y los nervios que controlan el corazón', modifiable: true },
    { factor: 'Consumo de tabaco', category: 'lifestyle', description: 'Daña las paredes de los vasos sanguíneos y reduce el oxígeno en la sangre', modifiable: true },
    { factor: 'Obesidad (IMC > 30)', category: 'lifestyle', description: 'El exceso de peso aumenta la carga de trabajo del corazón y la tensión metabólica', modifiable: true },
    { factor: 'Antecedentes familiares de enfermedad cardíaca', category: 'genetic', description: 'Los parientes de primer grado con enfermedad cardíaca temprana aumentan el riesgo', modifiable: false },
    { factor: 'Estilo de vida sedentario', category: 'lifestyle', description: 'La inactividad física debilita el músculo cardíaco y promueve la obesidad', modifiable: true },
    { factor: 'Estrés crónico', category: 'lifestyle', description: 'El estrés prolongado eleva la presión arterial y el ritmo cardíaco', modifiable: true },
    { factor: 'Consumo excesivo de alcohol', category: 'lifestyle', description: 'El consumo excesivo puede provocar miocardiopatía y arritmias', modifiable: true },
    { factor: 'Edad (Hombres >45, Mujeres >55)', category: 'demographic', description: 'El riesgo aumenta con la edad a medida que las arterias se endurecen', modifiable: false },
    { factor: 'Apnea del sueño', category: 'medical', description: 'Las bajadas repetidas de oxígeno sobrecargan el sistema cardiovascular', modifiable: true },
    { factor: 'Enfermedad renal crónica', category: 'medical', description: 'La disfunción renal afecta el equilibrio de fluidos y la presión arterial', modifiable: true },
  ],

  commonDiagnosticTests: [
    { test: 'Electrocardiograma (ECG/EKG)', purpose: 'Medir la actividad eléctrica del corazón y detectar ritmos anormales', whatToExpect: 'Prueba indolora con electrodos en el pecho, brazos y piernas. Dura 5-10 minutos.' },
    { test: 'Ecocardiograma', purpose: 'Imágenes por ultrasonido de la estructura y función del corazón', whatToExpect: 'Sonda en el pecho crea imágenes mediante ondas sonoras. Dura 30-60 minutos.' },
    { test: 'Prueba de esfuerzo (TMT)', purpose: 'Evaluar el funcionamiento del corazón durante el ejercicio', whatToExpect: 'Caminar/correr en una cinta mientras se monitorea el corazón. Dura 15-30 minutos.' },
    { test: 'Cateterismo cardíaco / Angiografía', purpose: 'Visualizar las arterias coronarias y medir las presiones', whatToExpect: 'Catéter insertado por el brazo o la ingle. Requiere anestesia local.' },
    { test: 'Angiografía por TC coronaria', purpose: 'Imágenes no invasivas de las arterias coronarias', whatToExpect: 'Tumbarse en un escáner de TC con inyección de medio de contraste.' },
    { test: 'Resonancia magnética cardíaca (RMC)', purpose: 'Imágenes detalladas del músculo cardíaco y el flujo sanguíneo', whatToExpect: 'Tumbarse en la máquina de resonancia magnética de 45 a 60 minutos.' },
    { test: 'Monitor Holter', purpose: 'Registrar el ritmo cardíaco durante 24-48 horas', whatToExpect: 'Llevar un dispositivo de ECG portátil durante las actividades normales.' },
    { test: 'Análisis de sangre (Lípidos, Troponina, BNP)', purpose: 'Comprobar el colesterol, marcadores de daño cardíaco e indicadores de insuficiencia cardíaca', whatToExpect: 'Extracción de sangre venosa.' },
    { test: 'Prueba de esfuerzo nuclear', purpose: 'Evaluar el flujo sanguíneo al músculo cardíaco en reposo y bajo estrés', whatToExpect: 'Inyección de un trazador radiactivo, toma de imágenes después del ejercicio.' },
    { test: 'Estudio electrofisiológico (EEF)', purpose: 'Mapear las vías eléctricas e identificar fuentes de arritmia', whatToExpect: 'Inserción de catéteres para registrar la actividad eléctrica del corazón.' },
  ],

  faqTemplates: [
    '¿Cuáles son los signos de advertencia de un ataque cardíaco?',
    '¿Se puede revertir la enfermedad cardíaca?',
    '¿Cuál es la diferencia entre un ataque cardíaco y un paro cardíaco?',
    '¿Con qué frecuencia debo revisarme el corazón?',
    '¿Qué alimentos son buenos para la salud del corazón?',
    '¿Puede el estrés realmente causar problemas cardíacos?',
    '¿Es hereditaria la enfermedad cardíaca?',
    '¿Cuál es la tasa de supervivencia después de un ataque cardíaco?',
    '¿Cuánto tiempo dura la recuperación después de una cirugía cardíaca?',
    '¿Puedo hacer ejercicio con una enfermedad cardíaca?',
    '¿Cuál es la diferencia entre angina y un ataque cardíaco?',
    '¿Son peligrosas las palpitaciones?',
    '¿Qué lectura de presión arterial es peligrosa?',
    '¿Se pueden desbloquear las arterias sin cirugía?',
    '¿Cómo reduzco mi riesgo de enfermedad cardíaca?',
  ],

  linkedTreatmentSlugs: [
    'angioplasty',
    'coronary-artery-bypass-surgery',
    'pacemaker-implantation',
    'heart-valve-surgery',
    'cardiac-catheterization',
    'stent-placement',
    'cardiac-rehabilitation',
    'icd-implantation',
    'heart-transplant',
    'tavr',
  ],

  costRanges: {
    consultation: { min: 50, max: 250, currency: 'USD' },
    ecg: { min: 20, max: 60, currency: 'USD' },
    echocardiogram: { min: 150, max: 400, currency: 'USD' },
    stressTest: { min: 200, max: 500, currency: 'USD' },
    angiography: { min: 1500, max: 4000, currency: 'USD' },
    angioplasty: { min: 15000, max: 40000, currency: 'USD' },
    bypassSurgery: { min: 25000, max: 70000, currency: 'USD' },
    pacemaker: { min: 15000, max: 50000, currency: 'USD' },
    valveSurgery: { min: 30000, max: 80000, currency: 'USD' },
  },

  emergencyIndicators: [
    'Dolor severo en el pecho que dura más de 15 minutos',
    'Dolor en el pecho con dificultad para respirar y sudoración',
    'Pérdida repentina del conocimiento',
    'Dificultad severa para respirar en reposo',
    'Latidos cardíacos extremadamente rápidos con mareos',
    'Dolor repentino y severo en las piernas con frialdad',
    'Dolor en el pecho que se irradia a la mandíbula o el brazo',
    'Labios o puntas de los dedos azulados',
    'Confusión acompañada de síntomas cardíacos',
    'Tos con mucosidad rosada y espumosa',
  ],

  lifestyleRecommendations: [
    'Realice 150 minutos de actividad aeróbica moderada a la semana',
    'Mantenga un peso saludable (IMC 18.5-24.9)',
    'Deje de fumar y evite el humo de segunda mano',
    'Limite el consumo de alcohol',
    'Practique técnicas de reducción de estrés (meditación, yoga)',
    'Controle la presión arterial regularmente en casa',
    'Duerma de 7 a 9 horas de calidad por noche',
    'Manténgase conectado socialmente y mentalmente activo',
    'Tome los medicamentos según lo prescrito',
    'Asista a chequeos cardíacos regulares',
  ],

  dietPatterns: {
    recommended: [
      'Pescado graso (salmón, caballa) 2-3 veces por semana',
      'Frutas y verduras frescas (5+ porciones diarias)',
      'Granos integrales (avena, arroz integral, quinua)',
      'Frutos secos y semillas (almendras, nueces, lino)',
      'Aceite de oliva como grasa principal para cocinar',
      'Legumbres y frijoles',
      'Productos lácteos bajos en grasa',
      'Proteínas magras (pollo, pavo)',
      'Verduras de hoja verde',
      'Bayas ricas en antioxidantes',
    ],
    avoid: [
      'Grasas trans y aceites hidrogenados',
      'Sodio excesivo (límite de 2000 mg diarios)',
      'Carnes procesadas y rojas',
      'Bebidas azucaradas y dulces',
      'Productos lácteos enteros',
      'Alimentos fritos y comida rápida',
      'Carbohidratos refinados',
      'Cafeína excesiva',
      'Vísceras ricas en colesterol',
      'Aperitivos envasados con sal añadida',
    ],
  },
};

export default cardiologyTemplateEs;
