/**
 * Gastroenterology Specialty Template
 *
 * Template patterns for digestive system conditions including stomach,
 * intestines, liver, pancreas, and gallbladder disorders.
 */

import type { SpecialtyTemplate } from './base-template';

export const gastroenterologyTemplate: SpecialtyTemplate = {
  specialty: 'Gastroenterology',
  specialistTitle: 'Gastroenterologist',
  specialistTitlePlural: 'Gastroenterologists',
  bodySystem: 'Digestive System',

  commonSymptomPatterns: [
    'Abdominal pain or cramping',
    'Nausea and vomiting',
    'Heartburn and acid reflux',
    'Bloating and gas',
    'Diarrhea or constipation',
    'Blood in stool (melena or hematochezia)',
    'Difficulty swallowing (dysphagia)',
    'Unexplained weight loss',
    'Loss of appetite',
    'Jaundice (yellowing of skin/eyes)',
    'Changes in bowel habits',
    'Feeling of incomplete evacuation',
    'Rectal pain or bleeding',
    'Excessive belching',
    'Abdominal distension',
  ],

  commonTreatmentTypes: [
    {
      type: 'medication',
      examples: [
        'Proton pump inhibitors (Omeprazole, Pantoprazole)',
        'H2 blockers (Ranitidine, Famotidine)',
        'Antacids (Aluminum/Magnesium hydroxide)',
        'Antispasmodics (Dicyclomine, Hyoscine)',
        'Laxatives (Lactulose, Polyethylene glycol)',
        'Anti-diarrheals (Loperamide)',
        'Antibiotics for H. pylori (Amoxicillin, Clarithromycin)',
        'Immunosuppressants for IBD (Azathioprine)',
        'Biologics for IBD (Infliximab, Adalimumab)',
        'Ursodeoxycholic acid for gallstones',
      ],
    },
    {
      type: 'procedure',
      examples: [
        'Upper GI endoscopy (EGD)',
        'Colonoscopy',
        'ERCP (Endoscopic Retrograde Cholangiopancreatography)',
        'Endoscopic ultrasound (EUS)',
        'Capsule endoscopy',
        'Liver biopsy',
        'Esophageal dilation',
        'Polypectomy',
        'Hemorrhoid banding',
        'Paracentesis',
      ],
    },
    {
      type: 'surgery',
      examples: [
        'Cholecystectomy (gallbladder removal)',
        'Appendectomy',
        'Hernia repair',
        'Fundoplication for GERD',
        'Colectomy',
        'Liver transplant',
        'Whipple procedure',
        'Bariatric surgery',
        'Hemorrhoidectomy',
        'Fistula repair',
      ],
    },
    {
      type: 'lifestyle',
      examples: [
        'Dietary modifications',
        'Low-FODMAP diet',
        'Gluten-free diet',
        'High-fiber diet',
        'Alcohol cessation',
        'Smoking cessation',
        'Stress management',
        'Regular meal timing',
        'Weight management',
        'Probiotics supplementation',
      ],
    },
  ],

  commonRiskFactors: [
    { factor: 'Poor dietary habits', category: 'lifestyle', description: 'High-fat, low-fiber diet increases digestive disorder risk', modifiable: true },
    { factor: 'Excessive alcohol consumption', category: 'lifestyle', description: 'Damages liver and stomach lining, increases cancer risk', modifiable: true },
    { factor: 'Smoking', category: 'lifestyle', description: 'Increases risk of GERD, ulcers, and GI cancers', modifiable: true },
    { factor: 'Obesity', category: 'lifestyle', description: 'Increases pressure on digestive system, raises GERD and fatty liver risk', modifiable: true },
    { factor: 'H. pylori infection', category: 'medical', description: 'Bacterial infection causing ulcers and gastritis', modifiable: true },
    { factor: 'Family history of GI diseases', category: 'genetic', description: 'Genetic predisposition to IBD, colorectal cancer', modifiable: false },
    { factor: 'NSAID overuse', category: 'lifestyle', description: 'Long-term use damages stomach lining', modifiable: true },
    { factor: 'Chronic stress', category: 'lifestyle', description: 'Exacerbates IBS and functional GI disorders', modifiable: true },
    { factor: 'Age over 50', category: 'demographic', description: 'Higher risk of colorectal cancer and diverticulosis', modifiable: false },
    { factor: 'Sedentary lifestyle', category: 'lifestyle', description: 'Slows digestion, increases constipation risk', modifiable: true },
    { factor: 'Hepatitis B/C infection', category: 'medical', description: 'Leads to chronic liver disease and cirrhosis', modifiable: true },
    { factor: 'Autoimmune conditions', category: 'medical', description: 'Associated with IBD and autoimmune hepatitis', modifiable: false },
  ],

  commonDiagnosticTests: [
    { test: 'Upper GI Endoscopy', purpose: 'Visualize esophagus, stomach, and duodenum directly', whatToExpect: 'Flexible tube with camera passed through mouth. Sedation provided. Takes 15-30 minutes.' },
    { test: 'Colonoscopy', purpose: 'Examine entire colon for polyps, cancer, or inflammation', whatToExpect: 'Scope inserted through rectum after bowel prep. Sedation provided. Takes 30-60 minutes.' },
    { test: 'Abdominal ultrasound', purpose: 'Image liver, gallbladder, pancreas, and bile ducts', whatToExpect: 'Gel applied to abdomen, probe moved over area. Painless. Takes 15-30 minutes.' },
    { test: 'CT scan of abdomen', purpose: 'Detailed cross-sectional imaging of digestive organs', whatToExpect: 'Lie in scanner, may drink contrast. Takes 15-30 minutes.' },
    { test: 'Stool tests (occult blood, culture, calprotectin)', purpose: 'Detect blood, infections, or inflammation markers', whatToExpect: 'Collect stool sample at home. Non-invasive.' },
    { test: 'Liver function tests (LFTs)', purpose: 'Assess liver health through blood markers', whatToExpect: 'Simple blood draw. Results in 1-2 days.' },
    { test: 'H. pylori breath test', purpose: 'Detect H. pylori bacterial infection', whatToExpect: 'Breathe into collection bag before and after drinking solution. Takes 30 minutes.' },
    { test: 'Liver biopsy', purpose: 'Examine liver tissue for damage or disease', whatToExpect: 'Needle inserted through skin under local anesthesia. Brief procedure, observation after.' },
    { test: 'FibroScan', purpose: 'Measure liver stiffness non-invasively', whatToExpect: 'Probe placed on skin over liver. Painless. Takes 10-15 minutes.' },
    { test: 'MRCP (MR Cholangiopancreatography)', purpose: 'Image bile ducts and pancreatic duct', whatToExpect: 'MRI scan focused on biliary system. Takes 30-45 minutes.' },
  ],

  faqTemplates: [
    'What foods trigger acid reflux?',
    'Is IBS the same as IBD?',
    'Can stomach ulcers be cured permanently?',
    'How often should I get a colonoscopy?',
    'What causes fatty liver and can it be reversed?',
    'Are gallstones dangerous?',
    'Can hemorrhoids go away on their own?',
    'What is the best diet for digestive health?',
    'Is blood in stool always serious?',
    'Can stress cause stomach problems?',
    'What is H. pylori and how is it treated?',
    'How do I know if I have a food intolerance?',
    'Can liver damage be reversed?',
    'What are the early signs of colon cancer?',
    'Is constipation a sign of something serious?',
  ],

  linkedTreatmentSlugs: [
    'colonoscopy',
    'endoscopy',
    'cholecystectomy',
    'ercp-procedure',
    'liver-biopsy',
    'hemorrhoid-treatment',
    'bariatric-surgery',
    'appendectomy',
    'hernia-repair',
    'liver-transplant',
  ],

  costRanges: {
    consultation: { min: 500, max: 2000, currency: 'INR' },
    endoscopy: { min: 3000, max: 10000, currency: 'INR' },
    colonoscopy: { min: 5000, max: 15000, currency: 'INR' },
    ultrasound: { min: 1000, max: 3000, currency: 'INR' },
    ctScan: { min: 3000, max: 10000, currency: 'INR' },
    liverBiopsy: { min: 10000, max: 25000, currency: 'INR' },
    cholecystectomy: { min: 50000, max: 150000, currency: 'INR' },
    appendectomy: { min: 40000, max: 100000, currency: 'INR' },
    ercp: { min: 25000, max: 60000, currency: 'INR' },
    liverTransplant: { min: 2000000, max: 4000000, currency: 'INR' },
  },

  emergencyIndicators: [
    'Severe abdominal pain with rigid abdomen',
    'Vomiting blood or coffee-ground material',
    'Black, tarry stools (melena)',
    'Large amount of bright red blood in stool',
    'Sudden severe pain with fever and chills',
    'Signs of dehydration with persistent vomiting',
    'Severe jaundice with confusion',
    'Abdominal distension with inability to pass gas',
    'Sharp pain that moves to right lower abdomen',
    'Swallowing difficulty with choking sensation',
  ],

  lifestyleRecommendations: [
    'Eat smaller, more frequent meals',
    'Chew food thoroughly and eat slowly',
    'Avoid lying down immediately after eating',
    'Stay hydrated with 8-10 glasses of water daily',
    'Include fiber-rich foods gradually',
    'Maintain regular meal times',
    'Limit spicy, fried, and fatty foods',
    'Practice stress reduction techniques',
    'Exercise regularly to promote digestion',
    'Avoid eating 2-3 hours before bedtime',
  ],

  dietPatterns: {
    recommended: [
      'High-fiber foods (whole grains, vegetables)',
      'Lean proteins (fish, chicken, tofu)',
      'Probiotic-rich foods (yogurt, kefir)',
      'Ginger and peppermint for digestive comfort',
      'Adequate water intake',
      'Bananas, rice, applesauce, toast (BRAT) for diarrhea',
      'Papaya and pineapple for digestive enzymes',
      'Fennel and chamomile tea',
      'Fermented foods (kimchi, sauerkraut)',
      'Oatmeal and other soluble fiber sources',
    ],
    avoid: [
      'Spicy foods that irritate stomach',
      'Fried and greasy foods',
      'Carbonated beverages',
      'Alcohol and caffeine',
      'High-fat dairy products',
      'Processed and fast foods',
      'Artificial sweeteners',
      'Raw vegetables if experiencing flare-up',
      'Acidic foods (tomatoes, citrus) if GERD present',
      'High-FODMAP foods if IBS diagnosed',
    ],
  },
};

export default gastroenterologyTemplate;
