/**
 * Neurology Specialty Template
 *
 * Template patterns for nervous system conditions including brain, spinal cord,
 * and peripheral nerve disorders.
 */

import type { SpecialtyTemplate } from './base-template';

export const neurologyTemplate: SpecialtyTemplate = {
  specialty: 'Neurology',
  specialistTitle: 'Neurologist',
  specialistTitlePlural: 'Neurologists',
  bodySystem: 'Nervous System',

  commonSymptomPatterns: [
    'Headaches and migraines',
    'Numbness or tingling',
    'Weakness in limbs',
    'Dizziness and vertigo',
    'Memory problems and confusion',
    'Seizures or convulsions',
    'Tremors or involuntary movements',
    'Balance and coordination problems',
    'Vision changes or double vision',
    'Speech difficulties (dysarthria, aphasia)',
    'Difficulty swallowing (dysphagia)',
    'Sleep disturbances',
    'Chronic pain (neuropathic)',
    'Difficulty walking (gait abnormalities)',
    'Loss of consciousness',
  ],

  commonTreatmentTypes: [
    {
      type: 'medication',
      examples: [
        'Anti-epileptic drugs (Levetiracetam, Valproate)',
        'Dopaminergic drugs (Levodopa, Pramipexole)',
        'Migraine medications (Triptans, CGRP inhibitors)',
        'Muscle relaxants (Baclofen, Tizanidine)',
        'Cholinesterase inhibitors (Donepezil)',
        'Disease-modifying drugs for MS (Interferons, Ocrelizumab)',
        'Antidepressants for neuropathic pain',
        'Anticonvulsants for nerve pain (Gabapentin, Pregabalin)',
        'Botulinum toxin injections',
        'Blood thinners for stroke prevention',
      ],
    },
    {
      type: 'therapy',
      examples: [
        'Physical therapy',
        'Speech therapy',
        'Occupational therapy',
        'Cognitive rehabilitation',
        'Vestibular rehabilitation',
        'Biofeedback therapy',
        'Transcranial magnetic stimulation (TMS)',
        'Cognitive behavioral therapy (CBT)',
        'Neurofeedback',
        'Aquatic therapy',
      ],
    },
    {
      type: 'procedure',
      examples: [
        'Lumbar puncture (spinal tap)',
        'Nerve blocks',
        'Deep brain stimulation (DBS)',
        'Vagus nerve stimulation',
        'Botox injections',
        'Epidural steroid injections',
        'Intrathecal pump implantation',
        'Gamma knife radiosurgery',
        'Nerve conduction studies',
      ],
    },
    {
      type: 'surgery',
      examples: [
        'Brain tumor resection',
        'Aneurysm clipping or coiling',
        'Carotid endarterectomy',
        'Microvascular decompression',
        'Epilepsy surgery',
        'Spinal cord surgery',
        'Shunt placement for hydrocephalus',
        'Carpal tunnel release',
        'Peripheral nerve surgery',
      ],
    },
  ],

  commonRiskFactors: [
    { factor: 'Age', category: 'demographic', description: 'Risk of neurological conditions increases with age', modifiable: false },
    { factor: 'Family history', category: 'genetic', description: 'Genetic predisposition to conditions like epilepsy, Parkinson\'s, Alzheimer\'s', modifiable: false },
    { factor: 'High blood pressure', category: 'medical', description: 'Major risk factor for stroke and dementia', modifiable: true },
    { factor: 'Diabetes', category: 'medical', description: 'Causes peripheral neuropathy and increases stroke risk', modifiable: true },
    { factor: 'Smoking', category: 'lifestyle', description: 'Increases risk of stroke and multiple sclerosis progression', modifiable: true },
    { factor: 'Head injuries', category: 'medical', description: 'Traumatic brain injuries increase dementia and seizure risk', modifiable: true },
    { factor: 'Excessive alcohol', category: 'lifestyle', description: 'Causes alcoholic neuropathy and brain damage', modifiable: true },
    { factor: 'High cholesterol', category: 'medical', description: 'Contributes to stroke risk through atherosclerosis', modifiable: true },
    { factor: 'Sedentary lifestyle', category: 'lifestyle', description: 'Associated with increased cognitive decline', modifiable: true },
    { factor: 'Sleep disorders', category: 'medical', description: 'Poor sleep linked to cognitive problems and headaches', modifiable: true },
    { factor: 'Stress and anxiety', category: 'lifestyle', description: 'Can trigger migraines and worsen neurological symptoms', modifiable: true },
    { factor: 'Environmental toxins', category: 'environmental', description: 'Heavy metals and pesticides linked to neurological damage', modifiable: true },
  ],

  commonDiagnosticTests: [
    { test: 'MRI of Brain/Spine', purpose: 'Detailed imaging of brain structures, tumors, and lesions', whatToExpect: 'Lie in tube-shaped scanner for 30-60 minutes. Loud noises. May need contrast.' },
    { test: 'CT scan', purpose: 'Quick imaging for stroke, bleeding, or trauma', whatToExpect: 'Lie on table passing through scanner. Takes 10-15 minutes.' },
    { test: 'EEG (Electroencephalogram)', purpose: 'Record brain electrical activity for seizures', whatToExpect: 'Electrodes placed on scalp. May last 30 minutes to several hours.' },
    { test: 'EMG/Nerve conduction study', purpose: 'Assess nerve and muscle function', whatToExpect: 'Needles inserted into muscles, electrical pulses applied. Some discomfort. Takes 30-60 minutes.' },
    { test: 'Lumbar puncture (Spinal tap)', purpose: 'Analyze cerebrospinal fluid for infections or MS', whatToExpect: 'Needle inserted into lower back. Local anesthesia. May cause headache afterward.' },
    { test: 'Carotid ultrasound', purpose: 'Assess blood flow to brain through neck arteries', whatToExpect: 'Gel applied to neck, probe moved over carotid arteries. Painless.' },
    { test: 'PET scan', purpose: 'Detect metabolic changes in brain tissue', whatToExpect: 'Radioactive tracer injected, images taken after 30-60 minutes. Total time 2-3 hours.' },
    { test: 'Evoked potentials', purpose: 'Measure nerve pathway response to stimuli', whatToExpect: 'Electrodes placed, visual/auditory/sensory stimuli applied. Takes 30-60 minutes.' },
    { test: 'Neuropsychological testing', purpose: 'Assess cognitive function and memory', whatToExpect: 'Series of written and verbal tests. Takes 2-4 hours.' },
    { test: 'Angiography (MRA/CTA)', purpose: 'Visualize blood vessels in brain', whatToExpect: 'MRI or CT with contrast to image blood vessels. Takes 30-60 minutes.' },
  ],

  faqTemplates: [
    'When is a headache serious enough to see a doctor?',
    'What is the difference between a stroke and a seizure?',
    'Can nerve damage be reversed?',
    'Is numbness and tingling a sign of something serious?',
    'What are the early signs of Parkinson\'s disease?',
    'Can migraines cause permanent brain damage?',
    'How is epilepsy different from seizures?',
    'Is dementia the same as Alzheimer\'s?',
    'Can stress cause neurological symptoms?',
    'What triggers multiple sclerosis flare-ups?',
    'Are tremors always a sign of Parkinson\'s?',
    'Can brain damage heal over time?',
    'What causes sudden memory loss?',
    'Is vertigo a brain problem or ear problem?',
    'Can neurological conditions be prevented?',
  ],

  linkedTreatmentSlugs: [
    'deep-brain-stimulation',
    'epilepsy-surgery',
    'stroke-treatment',
    'migraine-treatment',
    'brain-tumor-surgery',
    'lumbar-puncture',
    'nerve-block',
    'cognitive-rehabilitation',
    'vestibular-rehabilitation',
    'tms-therapy',
  ],

  costRanges: {
    consultation: { min: 800, max: 3000, currency: 'INR' },
    mri: { min: 8000, max: 20000, currency: 'INR' },
    ctScan: { min: 3000, max: 8000, currency: 'INR' },
    eeg: { min: 2000, max: 5000, currency: 'INR' },
    emg: { min: 3000, max: 8000, currency: 'INR' },
    lumbarPuncture: { min: 5000, max: 15000, currency: 'INR' },
    deepBrainStimulation: { min: 800000, max: 1500000, currency: 'INR' },
    brainSurgery: { min: 300000, max: 1000000, currency: 'INR' },
    strokeTreatment: { min: 200000, max: 800000, currency: 'INR' },
    epilepsySurgery: { min: 400000, max: 1000000, currency: 'INR' },
  },

  emergencyIndicators: [
    'Sudden severe headache (worst headache of life)',
    'FAST signs: Face drooping, Arm weakness, Speech difficulty, Time to call emergency',
    'Sudden loss of consciousness',
    'Seizure lasting more than 5 minutes',
    'First-time seizure',
    'Sudden vision loss',
    'Sudden severe confusion or disorientation',
    'Paralysis or severe weakness on one side',
    'Severe neck stiffness with headache and fever',
    'Head injury with loss of consciousness',
    'Sudden inability to speak or understand speech',
    'Severe dizziness with vomiting and imbalance',
  ],

  lifestyleRecommendations: [
    'Control blood pressure and diabetes',
    'Engage in regular physical exercise',
    'Maintain mental stimulation (puzzles, reading)',
    'Get 7-8 hours of quality sleep',
    'Manage stress through relaxation techniques',
    'Maintain social connections',
    'Follow a Mediterranean-style diet',
    'Limit alcohol consumption',
    'Avoid smoking',
    'Wear helmets during cycling and sports',
  ],

  dietPatterns: {
    recommended: [
      'Fatty fish (omega-3s for brain health)',
      'Leafy green vegetables',
      'Berries (antioxidants)',
      'Nuts and seeds',
      'Whole grains',
      'Olive oil',
      'Dark chocolate (in moderation)',
      'Turmeric and other anti-inflammatory spices',
      'Green tea',
      'Adequate hydration',
    ],
    avoid: [
      'Excessive alcohol',
      'Processed foods high in sodium',
      'Trans fats',
      'High-sugar foods and beverages',
      'Excessive caffeine (migraine trigger)',
      'MSG and artificial sweeteners (potential triggers)',
      'Red and processed meats in excess',
      'Aged cheeses if migraine-prone',
      'Refined carbohydrates',
      'Foods with nitrates (hot dogs, processed meats)',
    ],
  },
};

export default neurologyTemplate;
