/**
 * Orthopedics Specialty Template
 *
 * Template patterns for musculoskeletal conditions including bone, joint,
 * muscle, ligament, and tendon disorders.
 */

import type { SpecialtyTemplate } from './base-template';

export const orthopedicsTemplate: SpecialtyTemplate = {
  specialty: 'Orthopedics',
  specialistTitle: 'Orthopedic Surgeon',
  specialistTitlePlural: 'Orthopedic Surgeons',
  bodySystem: 'Musculoskeletal System',

  commonSymptomPatterns: [
    'Joint pain and stiffness',
    'Swelling around joints or bones',
    'Limited range of motion',
    'Muscle weakness',
    'Bone or joint deformity',
    'Difficulty walking or bearing weight',
    'Numbness or tingling in extremities',
    'Popping, clicking, or grinding sounds in joints',
    'Morning stiffness lasting more than 30 minutes',
    'Pain that worsens with activity',
    'Night pain disrupting sleep',
    'Visible bruising or discoloration',
    'Instability or giving way sensation',
    'Reduced grip strength',
    'Back pain radiating to legs',
  ],

  commonTreatmentTypes: [
    {
      type: 'medication',
      examples: [
        'NSAIDs (Ibuprofen, Naproxen, Diclofenac)',
        'Acetaminophen for pain relief',
        'Muscle relaxants (Cyclobenzaprine)',
        'Corticosteroid injections',
        'Hyaluronic acid injections (viscosupplementation)',
        'DMARDs for inflammatory arthritis',
        'Biologics (TNF inhibitors)',
        'Calcium and Vitamin D supplements',
        'Bisphosphonates for osteoporosis',
        'Topical pain relievers',
      ],
    },
    {
      type: 'therapy',
      examples: [
        'Physical therapy',
        'Occupational therapy',
        'Aquatic therapy',
        'Manual therapy and manipulation',
        'Electrical stimulation (TENS)',
        'Ultrasound therapy',
        'Heat and cold therapy',
        'Traction therapy',
        'Gait training',
        'Sports rehabilitation',
      ],
    },
    {
      type: 'procedure',
      examples: [
        'Joint aspiration (arthrocentesis)',
        'PRP (Platelet-Rich Plasma) injection',
        'Stem cell therapy',
        'Nerve blocks',
        'Radiofrequency ablation',
        'Extracorporeal shock wave therapy',
        'Manipulation under anesthesia',
      ],
    },
    {
      type: 'surgery',
      examples: [
        'Joint replacement (hip, knee, shoulder)',
        'Arthroscopic surgery',
        'Spinal fusion',
        'Fracture fixation (ORIF)',
        'Ligament reconstruction (ACL, PCL)',
        'Rotator cuff repair',
        'Carpal tunnel release',
        'Disc surgery (discectomy, laminectomy)',
        'Osteotomy',
        'Tendon repair',
      ],
    },
  ],

  commonRiskFactors: [
    { factor: 'Age-related wear and tear', category: 'demographic', description: 'Joint cartilage naturally degenerates with age', modifiable: false },
    { factor: 'Obesity and excess weight', category: 'lifestyle', description: 'Extra weight increases stress on weight-bearing joints', modifiable: true },
    { factor: 'Previous joint injuries', category: 'medical', description: 'Past trauma increases risk of arthritis and chronic problems', modifiable: false },
    { factor: 'Repetitive stress injuries', category: 'lifestyle', description: 'Repeated motions from work or sports strain joints and tendons', modifiable: true },
    { factor: 'Family history of bone/joint disease', category: 'genetic', description: 'Genetic factors influence osteoporosis and arthritis risk', modifiable: false },
    { factor: 'Poor posture', category: 'lifestyle', description: 'Improper alignment increases strain on spine and joints', modifiable: true },
    { factor: 'Sedentary lifestyle', category: 'lifestyle', description: 'Lack of exercise weakens muscles supporting joints', modifiable: true },
    { factor: 'Smoking', category: 'lifestyle', description: 'Impairs bone healing and increases osteoporosis risk', modifiable: true },
    { factor: 'Calcium/Vitamin D deficiency', category: 'lifestyle', description: 'Insufficient nutrients weaken bones', modifiable: true },
    { factor: 'High-impact sports participation', category: 'lifestyle', description: 'Contact sports increase injury risk', modifiable: true },
    { factor: 'Occupational hazards', category: 'environmental', description: 'Heavy lifting, vibration, and physical labor strain joints', modifiable: true },
    { factor: 'Female gender (for osteoporosis)', category: 'demographic', description: 'Postmenopausal women have higher bone loss rates', modifiable: false },
  ],

  commonDiagnosticTests: [
    { test: 'X-ray', purpose: 'Visualize bones, detect fractures, arthritis, and bone spurs', whatToExpect: 'Stand or lie still while images are taken. No pain, minimal radiation. Takes 10-15 minutes.' },
    { test: 'MRI (Magnetic Resonance Imaging)', purpose: 'Detailed imaging of soft tissues, cartilage, ligaments, and tendons', whatToExpect: 'Lie in tube-shaped scanner for 30-60 minutes. Loud noises, but painless.' },
    { test: 'CT scan', purpose: 'Cross-sectional bone imaging for complex fractures', whatToExpect: 'Lie on table passing through scanner. Takes 10-20 minutes. May need contrast dye.' },
    { test: 'Bone density scan (DEXA)', purpose: 'Measure bone mineral density for osteoporosis', whatToExpect: 'Lie on padded table while scanner passes over. Painless, takes 10-20 minutes.' },
    { test: 'Ultrasound', purpose: 'Real-time imaging of soft tissues and joint fluid', whatToExpect: 'Gel applied to skin, probe moved over area. Painless, takes 15-30 minutes.' },
    { test: 'Arthroscopy (diagnostic)', purpose: 'Direct visualization inside the joint', whatToExpect: 'Small camera inserted through tiny incision. Done under anesthesia.' },
    { test: 'EMG/Nerve conduction study', purpose: 'Assess nerve function and muscle response', whatToExpect: 'Electrodes placed on skin, mild electrical pulses applied. Some discomfort. Takes 30-60 minutes.' },
    { test: 'Blood tests (ESR, CRP, RF, Anti-CCP)', purpose: 'Detect inflammation and autoimmune markers', whatToExpect: 'Simple blood draw from arm vein. Results in 1-3 days.' },
    { test: 'Joint fluid analysis', purpose: 'Analyze fluid for infection, crystals, or inflammation', whatToExpect: 'Needle inserted into joint to withdraw fluid. Brief discomfort.' },
    { test: 'Bone scan', purpose: 'Detect bone abnormalities, infections, or tumors', whatToExpect: 'Radioactive tracer injected, images taken after 2-4 hours. Takes 30-60 minutes for imaging.' },
  ],

  faqTemplates: [
    'How long does it take to recover from joint replacement surgery?',
    'Can arthritis be cured or reversed?',
    'When should I see an orthopedic doctor for back pain?',
    'Is surgery always necessary for a torn ligament?',
    'What is the difference between a sprain and a strain?',
    'How can I prevent sports injuries?',
    'Are cortisone injections safe for long-term use?',
    'What causes osteoporosis and how can I prevent it?',
    'How do I know if I have a fracture or just a bruise?',
    'Can physical therapy replace surgery?',
    'What age is too old for joint replacement?',
    'How long should I rest an injured joint?',
    'What exercises help with arthritis pain?',
    'Is cracking joints harmful?',
    'What is the success rate of knee replacement surgery?',
  ],

  linkedTreatmentSlugs: [
    'knee-replacement-surgery',
    'hip-replacement-surgery',
    'arthroscopic-surgery',
    'spinal-fusion',
    'acl-reconstruction',
    'rotator-cuff-repair',
    'carpal-tunnel-surgery',
    'fracture-treatment',
    'physical-therapy',
    'prp-therapy',
  ],

  costRanges: {
    consultation: { min: 500, max: 2000, currency: 'INR' },
    xray: { min: 300, max: 800, currency: 'INR' },
    mri: { min: 5000, max: 15000, currency: 'INR' },
    ctScan: { min: 3000, max: 8000, currency: 'INR' },
    physicalTherapy: { min: 500, max: 1500, currency: 'INR' },
    steroidInjection: { min: 2000, max: 5000, currency: 'INR' },
    arthroscopy: { min: 80000, max: 200000, currency: 'INR' },
    kneeReplacement: { min: 200000, max: 500000, currency: 'INR' },
    hipReplacement: { min: 250000, max: 600000, currency: 'INR' },
    spinalSurgery: { min: 200000, max: 800000, currency: 'INR' },
  },

  emergencyIndicators: [
    'Visible bone deformity or bone protruding through skin',
    'Severe pain with inability to move the limb',
    'Loss of sensation in extremity after injury',
    'Severe swelling developing rapidly after injury',
    'Signs of infection (fever, red streaks, pus)',
    'Inability to bear weight after leg/ankle injury',
    'Severe back pain with loss of bladder/bowel control',
    'Numbness or weakness spreading in arms or legs',
    'Joint locked in position',
    'Severe pain in limb with cold or pale appearance',
  ],

  lifestyleRecommendations: [
    'Maintain a healthy weight to reduce joint stress',
    'Exercise regularly with low-impact activities',
    'Practice proper lifting techniques',
    'Use ergonomic equipment at work',
    'Warm up before exercise and cool down after',
    'Wear appropriate footwear for activities',
    'Take breaks from repetitive activities',
    'Strengthen core muscles for spine support',
    'Maintain good posture while sitting and standing',
    'Avoid high-impact activities if you have joint problems',
  ],

  dietPatterns: {
    recommended: [
      'Calcium-rich foods (dairy, fortified foods)',
      'Vitamin D sources (fatty fish, egg yolks, sunlight)',
      'Anti-inflammatory foods (fatty fish, berries, leafy greens)',
      'Lean proteins for muscle maintenance',
      'Omega-3 fatty acids (fish oil, walnuts)',
      'Collagen-boosting foods (bone broth, citrus fruits)',
      'Magnesium-rich foods (nuts, seeds, whole grains)',
      'Vitamin C for collagen synthesis',
      'Turmeric and ginger for natural anti-inflammatory effects',
      'Adequate hydration for joint lubrication',
    ],
    avoid: [
      'Excessive sugar which promotes inflammation',
      'Processed foods with preservatives',
      'Excessive alcohol which weakens bones',
      'High sodium foods causing water retention',
      'Trans fats that increase inflammation',
      'Excessive caffeine affecting calcium absorption',
      'Red meat in large quantities',
      'Refined carbohydrates',
      'Nightshade vegetables if they trigger symptoms',
      'Excessive omega-6 fatty acids',
    ],
  },
};

export default orthopedicsTemplate;
