/**
 * Seed comprehensive insurance providers for India
 */

import { Pool } from 'pg';

const pool = new Pool({ connectionString: process.env.DATABASE_URL || 'postgresql://taps@localhost:5432/aihealz' });

const INSURANCE_PROVIDERS = [
    // Private Insurance Companies
    {
        name: 'ICICI Lombard Health Insurance',
        slug: 'icici-lombard-health',
        providerType: 'private',
        licenseNumber: 'IRDAI/115',
        regulatoryBody: 'IRDAI',
        establishedYear: 2001,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'ICICI Lombard is one of the largest private sector general insurance companies in India, offering comprehensive health insurance solutions.',
        claimSettlementRatio: 96.5,
        website: 'https://www.icicilombard.com',
        customerCarePhone: '1800-2666-000',
        email: 'customersupport@icicilombard.com',
    },
    {
        name: 'Bajaj Allianz Health Insurance',
        slug: 'bajaj-allianz-health',
        providerType: 'private',
        licenseNumber: 'IRDAI/113',
        regulatoryBody: 'IRDAI',
        establishedYear: 2001,
        headquartersCity: 'Pune',
        headquartersCountry: 'India',
        description: 'Bajaj Allianz is a joint venture between Bajaj Finserv and Allianz SE, providing diverse health insurance products.',
        claimSettlementRatio: 95.8,
        website: 'https://www.bajajallianz.com',
        customerCarePhone: '1800-209-0144',
        email: 'baglobal@bajajallianz.co.in',
    },
    {
        name: 'Tata AIG Health Insurance',
        slug: 'tata-aig-health',
        providerType: 'private',
        licenseNumber: 'IRDAI/108',
        regulatoryBody: 'IRDAI',
        establishedYear: 2001,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'Tata AIG General Insurance offers health insurance backed by the trusted Tata brand and global expertise of AIG.',
        claimSettlementRatio: 94.2,
        website: 'https://www.tataaig.com',
        customerCarePhone: '1800-266-7780',
        email: 'customercare@tataaig.com',
    },
    {
        name: 'SBI Health Insurance',
        slug: 'sbi-health-insurance',
        providerType: 'private',
        licenseNumber: 'IRDAI/152',
        regulatoryBody: 'IRDAI',
        establishedYear: 2018,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'SBI General Insurance offers health coverage backed by State Bank of India, India\'s largest public sector bank.',
        claimSettlementRatio: 93.5,
        website: 'https://www.sbigeneral.in',
        customerCarePhone: '1800-102-1111',
        email: 'customer.care@sbigeneral.in',
    },
    {
        name: 'Reliance Health Insurance',
        slug: 'reliance-health-insurance',
        providerType: 'private',
        licenseNumber: 'IRDAI/103',
        regulatoryBody: 'IRDAI',
        establishedYear: 2000,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'Reliance General Insurance offers a wide range of health insurance products with extensive network coverage.',
        claimSettlementRatio: 92.8,
        website: 'https://www.reliancegeneral.co.in',
        customerCarePhone: '1800-102-9090',
        email: 'rgicl.care@relianceada.com',
    },
    {
        name: 'Care Health Insurance',
        slug: 'care-health-insurance',
        providerType: 'private',
        licenseNumber: 'IRDAI/130',
        regulatoryBody: 'IRDAI',
        establishedYear: 2012,
        headquartersCity: 'Gurgaon',
        headquartersCountry: 'India',
        description: 'Care Health Insurance (formerly Religare) is a standalone health insurer with innovative health products.',
        claimSettlementRatio: 94.5,
        website: 'https://www.careinsurance.com',
        customerCarePhone: '1800-102-4488',
        email: 'customer.care@careinsurance.com',
    },
    {
        name: 'Aditya Birla Health Insurance',
        slug: 'aditya-birla-health',
        providerType: 'private',
        licenseNumber: 'IRDAI/156',
        regulatoryBody: 'IRDAI',
        establishedYear: 2016,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'Aditya Birla Health Insurance offers innovative wellness-focused health insurance products.',
        claimSettlementRatio: 93.2,
        website: 'https://www.adityabirlacapital.com/healthinsurance',
        customerCarePhone: '1800-270-7000',
        email: 'care.healthinsurance@adityabirlacapital.com',
    },
    {
        name: 'ManipalCigna Health Insurance',
        slug: 'manipalcigna-health',
        providerType: 'private',
        licenseNumber: 'IRDAI/148',
        regulatoryBody: 'IRDAI',
        establishedYear: 2014,
        headquartersCity: 'Bangalore',
        headquartersCountry: 'India',
        description: 'ManipalCigna (TTK Healthcare partnered with Cigna) offers comprehensive health insurance solutions.',
        claimSettlementRatio: 91.5,
        website: 'https://www.manipalcigna.com',
        customerCarePhone: '1800-102-0333',
        email: 'customercare@manipalcigna.com',
    },
    {
        name: 'Cholamandalam MS Health Insurance',
        slug: 'chola-ms-health',
        providerType: 'private',
        licenseNumber: 'IRDAI/117',
        regulatoryBody: 'IRDAI',
        establishedYear: 2002,
        headquartersCity: 'Chennai',
        headquartersCountry: 'India',
        description: 'Cholamandalam MS General Insurance is part of Murugappa Group with MS&AD Insurance Group Holdings.',
        claimSettlementRatio: 90.8,
        website: 'https://www.cholainsurance.com',
        customerCarePhone: '1800-200-5544',
        email: 'customercare@chola-ms.com',
    },
    {
        name: 'Future Generali Health Insurance',
        slug: 'future-generali-health',
        providerType: 'private',
        licenseNumber: 'IRDAI/132',
        regulatoryBody: 'IRDAI',
        establishedYear: 2007,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'Future Generali India Insurance offers health insurance products with extensive coverage options.',
        claimSettlementRatio: 89.5,
        website: 'https://general.futuregenerali.in',
        customerCarePhone: '1800-220-233',
        email: 'fgloading@futuregenerali.in',
    },
    {
        name: 'Kotak Mahindra Health Insurance',
        slug: 'kotak-health-insurance',
        providerType: 'private',
        licenseNumber: 'IRDAI/107',
        regulatoryBody: 'IRDAI',
        establishedYear: 2015,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'Kotak Mahindra General Insurance provides health insurance backed by the Kotak Mahindra Group.',
        claimSettlementRatio: 92.3,
        website: 'https://www.kotakgeneral.com',
        customerCarePhone: '1800-266-4545',
        email: 'care@kotakgeneral.com',
    },
    {
        name: 'Royal Sundaram Health Insurance',
        slug: 'royal-sundaram-health',
        providerType: 'private',
        licenseNumber: 'IRDAI/102',
        regulatoryBody: 'IRDAI',
        establishedYear: 2000,
        headquartersCity: 'Chennai',
        headquartersCountry: 'India',
        description: 'Royal Sundaram General Insurance is one of the first private sector insurance companies in India.',
        claimSettlementRatio: 91.8,
        website: 'https://www.royalsundaram.in',
        customerCarePhone: '1800-568-9999',
        email: 'customercare@royalsundaram.in',
    },
    {
        name: 'Liberty General Health Insurance',
        slug: 'liberty-health-insurance',
        providerType: 'private',
        licenseNumber: 'IRDAI/150',
        regulatoryBody: 'IRDAI',
        establishedYear: 2013,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'Liberty General Insurance offers health insurance products with global service standards.',
        claimSettlementRatio: 88.5,
        website: 'https://www.libertyinsurance.in',
        customerCarePhone: '1800-266-5844',
        email: 'connect@libertyinsurance.in',
    },
    {
        name: 'Edelweiss Health Insurance',
        slug: 'edelweiss-health-insurance',
        providerType: 'private',
        licenseNumber: 'IRDAI/157',
        regulatoryBody: 'IRDAI',
        establishedYear: 2018,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'Edelweiss General Insurance offers innovative health insurance solutions with digital-first approach.',
        claimSettlementRatio: 87.5,
        website: 'https://www.edelweissinsurance.com',
        customerCarePhone: '1800-120-0030',
        email: 'support@edelweissinsurance.com',
    },
    {
        name: 'Go Digit Health Insurance',
        slug: 'go-digit-health',
        providerType: 'private',
        licenseNumber: 'IRDAI/158',
        regulatoryBody: 'IRDAI',
        establishedYear: 2017,
        headquartersCity: 'Bangalore',
        headquartersCountry: 'India',
        description: 'Digit Insurance is a tech-driven insurer offering simple and transparent health insurance products.',
        claimSettlementRatio: 96.0,
        website: 'https://www.godigit.com',
        customerCarePhone: '1800-258-5956',
        email: 'hello@godigit.com',
    },
    {
        name: 'Acko Health Insurance',
        slug: 'acko-health-insurance',
        providerType: 'private',
        licenseNumber: 'IRDAI/159',
        regulatoryBody: 'IRDAI',
        establishedYear: 2017,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'Acko is a digital-first insurance company offering quick and easy health insurance products.',
        claimSettlementRatio: 95.0,
        website: 'https://www.acko.com',
        customerCarePhone: '1800-266-2256',
        email: 'help@acko.com',
    },
    // Public Sector Insurance Companies
    {
        name: 'New India Assurance',
        slug: 'new-india-assurance',
        providerType: 'public',
        licenseNumber: 'IRDAI/001',
        regulatoryBody: 'IRDAI',
        establishedYear: 1919,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'New India Assurance is the largest general insurance company in India, government-owned with global presence.',
        claimSettlementRatio: 89.0,
        website: 'https://www.newindia.co.in',
        customerCarePhone: '1800-209-1415',
        email: 'customerhelp@newindia.co.in',
    },
    {
        name: 'Oriental Insurance',
        slug: 'oriental-insurance',
        providerType: 'public',
        licenseNumber: 'IRDAI/003',
        regulatoryBody: 'IRDAI',
        establishedYear: 1947,
        headquartersCity: 'New Delhi',
        headquartersCountry: 'India',
        description: 'Oriental Insurance Company is a public sector undertaking offering diverse health insurance products.',
        claimSettlementRatio: 87.5,
        website: 'https://www.orientalinsurance.org.in',
        customerCarePhone: '1800-118-485',
        email: 'consumer@orientalinsurance.co.in',
    },
    {
        name: 'United India Insurance',
        slug: 'united-india-insurance',
        providerType: 'public',
        licenseNumber: 'IRDAI/004',
        regulatoryBody: 'IRDAI',
        establishedYear: 1938,
        headquartersCity: 'Chennai',
        headquartersCountry: 'India',
        description: 'United India Insurance Company is one of the four public sector general insurers in India.',
        claimSettlementRatio: 86.8,
        website: 'https://www.uiic.co.in',
        customerCarePhone: '1800-425-2255',
        email: 'customercare@uiic.co.in',
    },
    // Government Schemes
    {
        name: 'CGHS - Central Government Health Scheme',
        slug: 'cghs',
        providerType: 'government',
        regulatoryBody: 'Ministry of Health and Family Welfare',
        establishedYear: 1954,
        headquartersCity: 'New Delhi',
        headquartersCountry: 'India',
        description: 'CGHS provides comprehensive healthcare to Central Government employees and pensioners.',
        claimSettlementRatio: 95.0,
        website: 'https://cghs.gov.in',
        customerCarePhone: '011-2306-1758',
    },
    {
        name: 'ECHS - Ex-Servicemen Contributory Health Scheme',
        slug: 'echs',
        providerType: 'government',
        regulatoryBody: 'Ministry of Defence',
        establishedYear: 2003,
        headquartersCity: 'New Delhi',
        headquartersCountry: 'India',
        description: 'ECHS provides healthcare to ex-servicemen and their dependents through a network of polyclinics.',
        claimSettlementRatio: 94.0,
        website: 'https://echs.gov.in',
        customerCarePhone: '011-2569-4968',
    },
    {
        name: 'ESIC - Employees State Insurance',
        slug: 'esic',
        providerType: 'government',
        regulatoryBody: 'Ministry of Labour and Employment',
        establishedYear: 1952,
        headquartersCity: 'New Delhi',
        headquartersCountry: 'India',
        description: 'ESIC provides social security and health insurance to workers in the organized sector.',
        claimSettlementRatio: 92.0,
        website: 'https://www.esic.in',
        customerCarePhone: '1800-11-2526',
    },
    {
        name: 'Aarogyasri - Telangana',
        slug: 'aarogyasri-telangana',
        providerType: 'government',
        regulatoryBody: 'Government of Telangana',
        establishedYear: 2007,
        headquartersCity: 'Hyderabad',
        headquartersCountry: 'India',
        description: 'Aarogyasri provides free health care to below poverty line families for serious ailments.',
        claimSettlementRatio: 93.0,
        website: 'https://www.aarogyasri.telangana.gov.in',
        customerCarePhone: '104',
    },
    {
        name: 'Chief Minister Insurance Scheme - Tamil Nadu',
        slug: 'cmchis-tamil-nadu',
        providerType: 'government',
        regulatoryBody: 'Government of Tamil Nadu',
        establishedYear: 2012,
        headquartersCity: 'Chennai',
        headquartersCountry: 'India',
        description: 'CMCHIS provides health insurance coverage to families in Tamil Nadu.',
        claimSettlementRatio: 91.0,
        website: 'https://www.cmchistn.com',
        customerCarePhone: '104',
    },
    {
        name: 'Bhamashah Swasthya Bima Yojana - Rajasthan',
        slug: 'bsby-rajasthan',
        providerType: 'government',
        regulatoryBody: 'Government of Rajasthan',
        establishedYear: 2015,
        headquartersCity: 'Jaipur',
        headquartersCountry: 'India',
        description: 'BSBY provides health coverage to families in Rajasthan with cashless treatment at empaneled hospitals.',
        claimSettlementRatio: 90.0,
        website: 'https://health.rajasthan.gov.in/bsby',
        customerCarePhone: '104',
    },
    {
        name: 'Mahatma Jyotiba Phule Jan Arogya Yojana - Maharashtra',
        slug: 'mjpjay-maharashtra',
        providerType: 'government',
        regulatoryBody: 'Government of Maharashtra',
        establishedYear: 2012,
        headquartersCity: 'Mumbai',
        headquartersCountry: 'India',
        description: 'MJPJAY provides health insurance to below poverty line families in Maharashtra.',
        claimSettlementRatio: 89.0,
        website: 'https://www.jeevandayee.gov.in',
        customerCarePhone: '155388',
    },
];

async function main() {
    console.log('Starting insurance provider seeding...\n');
    const client = await pool.connect();

    try {
        let created = 0;
        let skipped = 0;

        for (const provider of INSURANCE_PROVIDERS) {
            const existing = await client.query(
                'SELECT id FROM insurance_providers WHERE slug = $1',
                [provider.slug]
            );

            if (existing.rows.length > 0) {
                console.log(`  Skipped: ${provider.name} (already exists)`);
                skipped++;
                continue;
            }

            await client.query(`
                INSERT INTO insurance_providers (
                    name, slug, provider_type, license_number, regulatory_body,
                    established_year, headquarters_city, headquarters_country,
                    description, claim_settlement_ratio, website,
                    customer_care_phone, email, is_active, created_at, updated_at
                ) VALUES (
                    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, true, NOW(), NOW()
                )
            `, [
                provider.name,
                provider.slug,
                provider.providerType,
                provider.licenseNumber || null,
                provider.regulatoryBody,
                provider.establishedYear,
                provider.headquartersCity,
                provider.headquartersCountry,
                provider.description,
                provider.claimSettlementRatio || null,
                provider.website,
                provider.customerCarePhone || null,
                provider.email || null,
            ]);

            console.log(`  Created: ${provider.name}`);
            created++;
        }

        console.log(`\nCompleted!`);
        console.log(`   Created: ${created}`);
        console.log(`   Skipped: ${skipped}`);

    } finally {
        client.release();
        await pool.end();
    }
}

main().catch(console.error);
